# Generated by Django 4.0.4 on 2022-08-19 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('real_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User_to_master_language_syntax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_syntax_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language_syntax')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_to_master_framework_syntax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework_syntax_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.framework_syntax')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_seleceted_tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tree')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_mastered_language_syntax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_syntax_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language_syntax')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_mastered_framework_syntax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework_syntax_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.framework_syntax')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.job')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like_framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.framework')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ManyToManyField(blank=True, through='account.Like_company', to='main.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='framework',
            field=models.ManyToManyField(blank=True, through='account.Like_framework', to='main.framework'),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.ManyToManyField(blank=True, through='account.Like_job', to='main.job'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.ManyToManyField(blank=True, through='account.Like_language', to='main.language'),
        ),
        migrations.AddField(
            model_name='user',
            name='mastered_framework_syntax',
            field=models.ManyToManyField(blank=True, related_name='mastered_framework', through='account.User_mastered_framework_syntax', to='main.framework_syntax'),
        ),
        migrations.AddField(
            model_name='user',
            name='mastered_language_syntax',
            field=models.ManyToManyField(blank=True, related_name='mastered_language', through='account.User_mastered_language_syntax', to='main.language_syntax'),
        ),
        migrations.AddField(
            model_name='user',
            name='to_master_framework_syntax',
            field=models.ManyToManyField(blank=True, through='account.User_to_master_framework_syntax', to='main.framework_syntax'),
        ),
        migrations.AddField(
            model_name='user',
            name='to_master_language_syntax',
            field=models.ManyToManyField(blank=True, through='account.User_to_master_language_syntax', to='main.language_syntax'),
        ),
        migrations.AddField(
            model_name='user',
            name='tree_id',
            field=models.ManyToManyField(blank=True, through='account.User_seleceted_tree', to='main.tree'),
        ),
    ]
