# Generated by Django 4.1 on 2022-08-17 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Like_company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.company"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like_framework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "framework_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.framework"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like_job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.job"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like_language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.language"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_Password", models.CharField(max_length=45)),
                ("user_Email", models.CharField(max_length=45)),
                ("user_HP", models.TextField()),
                ("user_Birthday", models.DateTimeField()),
                (
                    "company",
                    models.ManyToManyField(
                        blank=True, through="account.Like_company", to="main.company"
                    ),
                ),
                (
                    "framework",
                    models.ManyToManyField(
                        blank=True,
                        through="account.Like_framework",
                        to="main.framework",
                    ),
                ),
                (
                    "job",
                    models.ManyToManyField(
                        blank=True, through="account.Like_job", to="main.job"
                    ),
                ),
                (
                    "language",
                    models.ManyToManyField(
                        blank=True, through="account.Like_language", to="main.language"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_to_master_language_syntax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_syntax_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.language_syntax",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_to_master_framework_syntax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "framework_syntax_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.framework_syntax",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_seleceted_tree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tree_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.tree"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_mastered_language_syntax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_syntax_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.language_syntax",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_mastered_framework_syntax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "framework_syntax_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.framework_syntax",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="mastered_framework_syntax",
            field=models.ManyToManyField(
                blank=True,
                related_name="mastered_framework",
                through="account.User_mastered_framework_syntax",
                to="main.framework_syntax",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mastered_language_syntax",
            field=models.ManyToManyField(
                blank=True,
                related_name="mastered_language",
                through="account.User_mastered_language_syntax",
                to="main.language_syntax",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="to_master_framework_syntax",
            field=models.ManyToManyField(
                blank=True,
                through="account.User_to_master_framework_syntax",
                to="main.framework_syntax",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="to_master_language_syntax",
            field=models.ManyToManyField(
                blank=True,
                through="account.User_to_master_language_syntax",
                to="main.language_syntax",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tree_id",
            field=models.ManyToManyField(
                blank=True, through="account.User_seleceted_tree", to="main.tree"
            ),
        ),
        migrations.AddField(
            model_name="like_language",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.user"
            ),
        ),
        migrations.AddField(
            model_name="like_job",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.user"
            ),
        ),
        migrations.AddField(
            model_name="like_framework",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.user"
            ),
        ),
        migrations.AddField(
            model_name="like_company",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.user"
            ),
        ),
    ]
